# Generated by Django 5.1.2 on 2024-10-25 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.BigIntegerField(unique=True)),
                ('role_def', models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('STAFF', 'Staff')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('availability', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo')),
            ],
        ),
    ]
