# Generated by Django 5.1.2 on 2024-10-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_patient_patients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
