# Generated by Django 5.1.2 on 2024-10-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_doctors_doctor_rename_patients_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='Female', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='Female', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role_def',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('STAFF', 'Staff')], default='Patient', max_length=20),
        ),
    ]
