# Generated by Django 5.1.2 on 2024-10-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_doctor_availability_alter_doctor_sex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'userinfo'},
        ),
    ]
