# Generated by Django 5.1.2 on 2024-10-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': ['userinfo', 'mobile_number']},
        ),
    ]
