# Generated by Django 5.1.2 on 2024-10-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'userinfo'},
        ),
    ]
