# Generated by Django 5.1.2 on 2024-10-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userinfo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
