# Generated by Django 5.1.2 on 2024-10-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
