# Generated by Django 5.1.2 on 2024-11-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_delete_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'userinfo'},
        ),
    ]
