# Generated by Django 5.1.2 on 2024-11-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_delete_appointment'),
        ('doctor', '0006_appointmentslot'),
        ('patient', '0003_rename_user_info_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('INPROCESS', 'Inprocess'), ('CONFIRMED', 'Confirmed'), ('UNSUCCESSFUL', 'Unsuccessful'), ('COMPLETED', 'Completed')], default='INPROCESS', max_length=20)),
                ('paid', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5)),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('doctorsnote', models.TextField(default='')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.appointmentslot')),
            ],
        ),
    ]
