# Generated by Django 5.1.2 on 2024-11-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorsnote',
            field=models.TextField(blank=True, default=''),
        ),
    ]
