# Generated by Django 5.1.2 on 2024-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='stat',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('UNSUCCESSFUL', 'Unsuccessful'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20),
        ),
    ]
