# Generated by Django 5.1.2 on 2024-11-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
