# Generated by Django 5.1.2 on 2024-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorsnote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
