# Generated by Django 5.1.2 on 2024-11-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_doctorsnote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='paid',
        ),
    ]
