# Generated by Django 5.1.2 on 2024-11-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_remove_appointment_paid'),
        ('hospital_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='test',
            field=models.ManyToManyField(blank=True, to='hospital_test.test'),
        ),
    ]
