# Generated by Django 5.1.2 on 2024-10-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['dept_name']},
        ),
    ]
