# Generated by Django 5.1.2 on 2024-10-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
