# Generated by Django 5.1.2 on 2024-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dayofstarting',
            field=models.DateField(auto_now=True),
        ),
    ]
