# Generated by Django 5.1.2 on 2024-11-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_appointmentslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentslot',
            options={'ordering': ['doctor', 'day_of_week', 'session']},
        ),
        migrations.RenameField(
            model_name='appointmentslot',
            old_name='slot',
            new_name='session',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('doctor', 'date', 'day_of_week', 'session')},
        ),
    ]
