# Generated by Django 5.1.2 on 2024-11-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_appointmentslot_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentslot',
            unique_together={('doctor', 'day_of_week', 'session')},
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='date',
        ),
    ]
