# Generated by Django 5.1.2 on 2024-11-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='cost',
        ),
    ]
